/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._gui02;

/**
 *
 * @author Gerardo
 */
import javax.swing.JOptionPane; //clase para mostrar alertas en pantalla
import java.util.Calendar;      //para obtener la fecha de la computadora
import java.text.SimpleDateFormat; //para dar formato fecha/hora
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloCarrera = new javax.swing.JLabel();
        botonAlerta = new javax.swing.JButton();
        botonCambiarTitulo = new javax.swing.JButton();
        caja1 = new javax.swing.JTextField();
        botonDeshabilitar = new javax.swing.JButton();
        botonHabilitar = new javax.swing.JButton();
        labelFechaHora = new javax.swing.JLabel();
        botonFechaHora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("20012002049 - Gerardo");
        setBackground(new java.awt.Color(204, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloCarrera.setBackground(new java.awt.Color(255, 204, 204));
        tituloCarrera.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        tituloCarrera.setForeground(new java.awt.Color(255, 0, 51));
        tituloCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCarrera.setText("Sistemas 2024");
        tituloCarrera.setToolTipText("Esta es la mejor carrera de la UNAH");
        tituloCarrera.setOpaque(true);

        botonAlerta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAlerta.setForeground(new java.awt.Color(51, 102, 255));
        botonAlerta.setText("Click aqui");
        botonAlerta.setToolTipText("ayuda para este boton");
        botonAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlertaActionPerformed(evt);
            }
        });

        botonCambiarTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCambiarTitulo.setText("Cambiar el titulo de la Ventana");
        botonCambiarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarTituloActionPerformed(evt);
            }
        });

        caja1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        caja1.setText("escriba aqui");

        botonDeshabilitar.setText("Deshabilitar caja de texto");
        botonDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeshabilitarActionPerformed(evt);
            }
        });

        botonHabilitar.setText("Habilitar caja de texto");
        botonHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabilitarActionPerformed(evt);
            }
        });

        labelFechaHora.setBackground(new java.awt.Color(255, 204, 102));
        labelFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFechaHora.setText("jLabel1");
        labelFechaHora.setOpaque(true);

        botonFechaHora.setText("Ver Fecha y Hora");
        botonFechaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFechaHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonCambiarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tituloCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelFechaHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caja1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonDeshabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonHabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCambiarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonDeshabilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonHabilitar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(botonFechaHora)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //forzar la aplicacion del color de fondo
        this.getContentPane().setBackground( this.getBackground() );
    }//GEN-LAST:event_formWindowOpened

    private void botonAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlertaActionPerformed
        //evento que se ejecuta cuando hacen click en el boton
        //mostrar una alerta en pantalla
        JOptionPane.showMessageDialog(this, "Bienvenido Estudiante");
        //cambiarle el texto por programacion al JLabel llamado tituloCarrera
        tituloCarrera.setText("Ing. En Sistemas");
    }//GEN-LAST:event_botonAlertaActionPerformed

    private void botonCambiarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarTituloActionPerformed
        //cambiar el texto de la barra de titulo del JFrame (ventana)
        this.setTitle("PUMAS UNAH");
    }//GEN-LAST:event_botonCambiarTituloActionPerformed

    private void botonDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeshabilitarActionPerformed
        //impedir escribir en la caja de texto llamada caja1
        caja1.setEditable(false);
        //impedir que se pueda ingresar a la caja de texto
        //caja1.setEnabled(false);
        //ocultar caja1
        //caja1.setVisible(false);
    }//GEN-LAST:event_botonDeshabilitarActionPerformed

    private void botonHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabilitarActionPerformed
        //permitir escribir en la caja de texto llamada caja1
        caja1.setEditable(true);
        //permitir que se pueda ingresar a la caja de texto
        //caja1.setEnabled(true);
        //mostrar caja1
        //caja1.setVisible(true);
    }//GEN-LAST:event_botonHabilitarActionPerformed

    private void botonFechaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFechaHoraActionPerformed
        //colocar la fecha y hora en el label llamado labelFechaHora
        //para ello necesitamos importar a la clase java.util.Calendar
        //y para darle formato de fecha hora importamos la clase java.text.SimpleDateFormat
        //crear un objeto Calendar con la fecha de la computadora
        Calendar fecha = Calendar.getInstance();
        //poner una fecha hora fija (para pruebas)
        //fecha.set(2024, 10, 20, 17, 30, 25);
        //crear un objeto para dar formato fecha/hora a lo contenido en el objeto fecha
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY hh:mm:ss a");
        labelFechaHora.setText( formato.format( fecha.getTime() ) );
    }//GEN-LAST:event_botonFechaHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlerta;
    private javax.swing.JButton botonCambiarTitulo;
    private javax.swing.JButton botonDeshabilitar;
    private javax.swing.JButton botonFechaHora;
    private javax.swing.JButton botonHabilitar;
    private javax.swing.JTextField caja1;
    private javax.swing.JLabel labelFechaHora;
    private javax.swing.JLabel tituloCarrera;
    // End of variables declaration//GEN-END:variables
}
