/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._gui08;

/**
 *
 * @author Gerardo
 */
import javax.swing.DefaultListModel; //clase para crear modelo de JList
import javax.swing.JOptionPane;
public class Ventana1 extends javax.swing.JFrame {

    //aqui podemos declarar variables globales
    //estas estan disponible desde cualquier evento o funcion
    //de esta clase
    DefaultListModel modelo;
    
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        caja = new javax.swing.JTextField();
        botonAgregar1 = new javax.swing.JButton();
        botonAgregar2 = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("20012002049 Gerardo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Honduras", "Guatemala", "El Salvador" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista);

        caja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botonAgregar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregar1.setText("Agregar (metodo 1)");
        botonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar1ActionPerformed(evt);
            }
        });

        botonAgregar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregar2.setText("Agregar (metodo 2)");
        botonAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar2ActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caja, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //vamos a llenar al JList llamado lista con nombres animales
        //primero vamos a instanciar un nuevo objeto para el modelo de datos
        modelo = new DefaultListModel();
        //colocar datos de prueba en el modelo
        modelo.addElement("Perro");
        modelo.addElement("Gato");
        modelo.addElement("Loro");
        modelo.addElement("Gallina");
        //apuntar el modelo hacia el JList
        lista.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened

    private void botonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar1ActionPerformed
        //metodo 1: agregar al JList lo que escribamos en la caja de texto
        //validacion: solo si la caja de texto tiene contenido
        if( caja.getText().trim().length() > 0 ){
            modelo.addElement(caja.getText());
            //dejar en blanco la caja de texto
            caja.setText("");
        }
    }//GEN-LAST:event_botonAgregar1ActionPerformed

    private void botonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar2ActionPerformed
        //metodo 2: agregar al JList lo leido desde un JOptionPane
        //depositar en una variable lo capturado:
        String x = JOptionPane.showInputDialog(this,"Digite un nombre de animal: ");
        //validar que x no venga null
        //cuando x vienen null quiere decir que se cancelaron el InputDialog
        if( x != null ){
            //validar que x no venga en blanco
            if( x.trim().length() > 0 ){
                modelo.addElement(x);
            }
        }
    }//GEN-LAST:event_botonAgregar2ActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //verificar que se ha seleccionado un animal en la lista
        if( lista.getSelectedIndex() == -1 ){
            JOptionPane.showMessageDialog(this, "Seleccione un animal");
            return; //no sigue
        }
        //mostrar un InputDialog con el valor del animal seleccionado
        String actual = lista.getSelectedValue();
        String nuevo = JOptionPane.showInputDialog(this,"Nuevo nombre: ",actual);
        if( nuevo != null ){
            if( nuevo.trim().length() > 0 ){
                //reemplazar el valor en el modelo para la posicion en la lista
                modelo.setElementAt(nuevo, lista.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar1;
    private javax.swing.JButton botonAgregar2;
    private javax.swing.JButton botonEditar;
    private javax.swing.JTextField caja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    // End of variables declaration//GEN-END:variables
}
